import { IProductCollection } from "@/types";

export const productData = {
  jackets: [
    {
      id: 1,
      title: "Classic Leather Jacket",
      description: "A timeless black leather jacket with a sleek design.",
      image: "https://example.com/images/leather_jacket.jpg",
      price: 120.99,
      category: "Jackets",
    },
    {
      id: 2,
      title: "Denim Jacket",
      description: "Stylish blue denim jacket perfect for casual wear.",
      image: "https://example.com/images/denim_jacket.jpg",
      price: 75.49,
      category: "Jackets",
    },
    {
      id: 3,
      title: "Bomber Jacket",
      description: "Trendy bomber jacket with a comfortable fit.",
      image: "https://example.com/images/bomber_jacket.jpg",
      price: 89.99,
      category: "Jackets",
    },
    {
      id: 4,
      title: "Parka Jacket",
      description: "Warm parka jacket with a fur-lined hood.",
      image: "https://example.com/images/parka_jacket.jpg",
      price: 149.99,
      category: "Jackets",
    },
    {
      id: 5,
      title: "Windbreaker Jacket",
      description: "Lightweight windbreaker jacket for outdoor activities.",
      image: "https://example.com/images/windbreaker_jacket.jpg",
      price: 59.99,
      category: "Jackets",
    },
    {
      id: 6,
      title: "Varsity Jacket",
      description: "Classic varsity jacket with a sporty look.",
      image: "https://example.com/images/varsity_jacket.jpg",
      price: 99.99,
      category: "Jackets",
    },
    {
      id: 7,
      title: "Peacoat Jacket",
      description: "Elegant peacoat jacket with a double-breasted design.",
      image: "https://example.com/images/peacoat_jacket.jpg",
      price: 129.99,
      category: "Jackets",
    },
    {
      id: 8,
      title: "Trench Coat",
      description: "Classic trench coat for a sophisticated look.",
      image: "https://example.com/images/trench_coat.jpg",
      price: 139.99,
      category: "Jackets",
    },
    {
      id: 9,
      title: "Quilted Jacket",
      description: "Comfortable quilted jacket with extra padding.",
      image: "https://example.com/images/quilted_jacket.jpg",
      price: 79.99,
      category: "Jackets",
    },
    {
      id: 10,
      title: "Hooded Jacket",
      description: "Casual hooded jacket perfect for everyday wear.",
      image: "https://example.com/images/hooded_jacket.jpg",
      price: 69.99,
      category: "Jackets",
    },
    {
      id: 11,
      title: "Field Jacket",
      description: "Durable field jacket with multiple pockets.",
      image: "https://example.com/images/field_jacket.jpg",
      price: 110.99,
      category: "Jackets",
    },
    {
      id: 12,
      title: "Fleece Jacket",
      description: "Warm fleece jacket for cold weather.",
      image: "https://example.com/images/fleece_jacket.jpg",
      price: 55.99,
      category: "Jackets",
    },
    {
      id: 13,
      title: "Suede Jacket",
      description: "Stylish suede jacket with a soft touch.",
      image: "https://example.com/images/suede_jacket.jpg",
      price: 115.99,
      category: "Jackets",
    },
    {
      id: 14,
      title: "Blazer Jacket",
      description: "Smart blazer jacket for formal occasions.",
      image: "https://example.com/images/blazer_jacket.jpg",
      price: 105.99,
      category: "Jackets",
    },
    {
      id: 15,
      title: "Down Jacket",
      description: "Insulated down jacket for extreme cold.",
      image: "https://example.com/images/down_jacket.jpg",
      price: 159.99,
      category: "Jackets",
    },
  ],
  sportswear: [
    {
      id: 1,
      title: "Running Shoes",
      description: "Lightweight running shoes designed for maximum comfort.",
      image: "https://example.com/images/running_shoes.jpg",
      price: 59.99,
      category: "Sportswear",
    },
    {
      id: 2,
      title: "Yoga Pants",
      description: "Flexible yoga pants perfect for any workout.",
      image: "https://example.com/images/yoga_pants.jpg",
      price: 39.99,
      category: "Sportswear",
    },
    {
      id: 3,
      title: "Fitness Tracker",
      description: "Wearable fitness tracker to monitor your activity.",
      image: "https://example.com/images/fitness_tracker.jpg",
      price: 129.99,
      category: "Sportswear",
    },
    {
      id: 4,
      title: "Sports Jacket",
      description: "Lightweight sports jacket for outdoor activities.",
      image: "https://example.com/images/sports_jacket.jpg",
      price: 49.99,
      category: "Sportswear",
    },
    {
      id: 5,
      title: "Basketball Shorts",
      description:
        "Comfortable basketball shorts with moisture-wicking fabric.",
      image: "https://example.com/images/basketball_shorts.jpg",
      price: 25.99,
      category: "Sportswear",
    },
    {
      id: 6,
      title: "Compression Shirt",
      description: "Tight-fitting compression shirt for enhanced performance.",
      image: "https://example.com/images/compression_shirt.jpg",
      price: 29.99,
      category: "Sportswear",
    },
    {
      id: 7,
      title: "Sports Bra",
      description: "Supportive sports bra for high-impact activities.",
      image: "https://example.com/images/sports_bra.jpg",
      price: 35.99,
      category: "Sportswear",
    },
    {
      id: 8,
      title: "Training Socks",
      description: "Comfortable and breathable training socks.",
      image: "https://example.com/images/training_socks.jpg",
      price: 12.99,
      category: "Sportswear",
    },
    {
      id: 9,
      title: "Track Pants",
      description: "Lightweight track pants for running and training.",
      image: "https://example.com/images/track_pants.jpg",
      price: 45.99,
      category: "Sportswear",
    },
    {
      id: 10,
      title: "Sports Cap",
      description: "Breathable sports cap to keep you cool.",
      image: "https://example.com/images/sports_cap.jpg",
      price: 19.99,
      category: "Sportswear",
    },
    {
      id: 11,
      title: "Sweatband",
      description: "Absorbent sweatband for intense workouts.",
      image: "https://example.com/images/sweatband.jpg",
      price: 9.99,
      category: "Sportswear",
    },
    {
      id: 12,
      title: "Running Tights",
      description: "Form-fitting running tights for optimal performance.",
      image: "https://example.com/images/running_tights.jpg",
      price: 39.99,
      category: "Sportswear",
    },
    {
      id: 13,
      title: "Training Gloves",
      description: "Protective training gloves for weightlifting.",
      image: "https://example.com/images/training_gloves.jpg",
      price: 24.99,
      category: "Sportswear",
    },
    {
      id: 14,
      title: "Hiking Boots",
      description: "Durable hiking boots for all terrains.",
      image: "https://example.com/images/hiking_boots.jpg",
      price: 89.99,
      category: "Sportswear",
    },
    {
      id: 15,
      title: "Cycling Jersey",
      description: "Breathable cycling jersey with a comfortable fit.",
      image: "https://example.com/images/cycling_jersey.jpg",
      price: 59.99,
      category: "Sportswear",
    },
  ],
  shoes: [
    {
      id: 1,
      title: "Running Shoes",
      description: "Lightweight running shoes designed for maximum comfort.",
      image: "https://example.com/images/running_shoes.jpg",
      price: 59.99,
      category: "Shoes",
    },
    {
      id: 2,
      title: "Basketball Shoes",
      description: "High-top basketball shoes with excellent ankle support.",
      image: "https://example.com/images/basketball_shoes.jpg",
      price: 89.99,
      category: "Shoes",
    },
    {
      id: 3,
      title: "Soccer Cleats",
      description: "Durable soccer cleats for firm ground surfaces.",
      image: "https://example.com/images/soccer_cleats.jpg",
      price: 79.99,
      category: "Shoes",
    },
    {
      id: 4,
      title: "Tennis Shoes",
      description: "Comfortable tennis shoes with a non-marking sole.",
      image: "https://example.com/images/tennis_shoes.jpg",
      price: 69.99,
      category: "Shoes",
    },
    {
      id: 5,
      title: "Hiking Boots",
      description: "Rugged hiking boots for all terrains.",
      image: "https://example.com/images/hiking_boots.jpg",
      price: 99.99,
      category: "Shoes",
    },
    {
      id: 6,
      title: "Casual Sneakers",
      description: "Stylish casual sneakers for everyday wear.",
      image: "https://example.com/images/casual_sneakers.jpg",
      price: 49.99,
      category: "Shoes",
    },
    {
      id: 7,
      title: "Dress Shoes",
      description: "Elegant dress shoes for formal occasions.",
      image: "https://example.com/images/dress_shoes.jpg",
      price: 109.99,
      category: "Shoes",
    },
    {
      id: 8,
      title: "Slip-On Shoes",
      description: "Convenient slip-on shoes with a comfortable fit.",
      image: "https://example.com/images/slip_on_shoes.jpg",
      price: 39.99,
      category: "Shoes",
    },
    {
      id: 9,
      title: "Loafers",
      description: "Classic loafers for a casual yet polished look.",
      image: "https://example.com/images/loafers.jpg",
      price: 69.99,
      category: "Shoes",
    },
    {
      id: 10,
      title: "Sandals",
      description: "Comfortable sandals for warm weather.",
      image: "https://example.com/images/sandals.jpg",
      price: 29.99,
      category: "Shoes",
    },
    {
      id: 11,
      title: "Running Shoes",
      description: "High-performance running shoes for athletes.",
      image: "https://example.com/images/high_performance_running_shoes.jpg",
      price: 99.99,
      category: "Shoes",
    },
    {
      id: 12,
      title: "Golf Shoes",
      description: "Water-resistant golf shoes with excellent grip.",
      image: "https://example.com/images/golf_shoes.jpg",
      price: 79.99,
      category: "Shoes",
    },
    {
      id: 13,
      title: "Skate Shoes",
      description: "Durable skate shoes with a grippy sole.",
      image: "https://example.com/images/skate_shoes.jpg",
      price: 59.99,
      category: "Shoes",
    },
    {
      id: 14,
      title: "Climbing Shoes",
      description: "Specialized climbing shoes with a snug fit.",
      image: "https://example.com/images/climbing_shoes.jpg",
      price: 89.99,
      category: "Shoes",
    },
    {
      id: 15,
      title: "Water Shoes",
      description: "Quick-drying water shoes for aquatic activities.",
      image: "https://example.com/images/water_shoes.jpg",
      price: 39.99,
      category: "Shoes",
    },
  ],
  accessories: [
    {
      id: 1,
      title: "Sunglasses",
      description: "Stylish sunglasses with UV protection.",
      image: "https://example.com/images/sunglasses.jpg",
      price: 25.99,
      category: "Accessories",
    },
    {
      id: 2,
      title: "Leather Wallet",
      description: "Durable leather wallet with multiple compartments.",
      image: "https://example.com/images/leather_wallet.jpg",
      price: 49.99,
      category: "Accessories",
    },
    {
      id: 3,
      title: "Wristwatch",
      description: "Elegant wristwatch with a stainless steel band.",
      image: "https://example.com/images/wristwatch.jpg",
      price: 129.99,
      category: "Accessories",
    },
    {
      id: 4,
      title: "Baseball Cap",
      description: "Casual baseball cap with adjustable strap.",
      image: "https://example.com/images/baseball_cap.jpg",
      price: 19.99,
      category: "Accessories",
    },
    {
      id: 5,
      title: "Scarf",
      description: "Warm and stylish scarf for cold weather.",
      image: "https://example.com/images/scarf.jpg",
      price: 29.99,
      category: "Accessories",
    },
    {
      id: 6,
      title: "Backpack",
      description: "Spacious backpack with multiple pockets.",
      image: "https://example.com/images/backpack.jpg",
      price: 69.99,
      category: "Accessories",
    },
    {
      id: 7,
      title: "Belt",
      description: "Leather belt with a classic buckle.",
      image: "https://example.com/images/belt.jpg",
      price: 34.99,
      category: "Accessories",
    },
    {
      id: 8,
      title: "Beanie",
      description: "Comfortable beanie for chilly days.",
      image: "https://example.com/images/beanie.jpg",
      price: 15.99,
      category: "Accessories",
    },
    {
      id: 9,
      title: "Tie",
      description: "Silk tie for formal occasions.",
      image: "https://example.com/images/tie.jpg",
      price: 24.99,
      category: "Accessories",
    },
    {
      id: 10,
      title: "Gloves",
      description: "Warm gloves with a touchscreen-compatible design.",
      image: "https://example.com/images/gloves.jpg",
      price: 19.99,
      category: "Accessories",
    },
    {
      id: 11,
      title: "Earrings",
      description: "Elegant earrings with a minimalist design.",
      image: "https://example.com/images/earrings.jpg",
      price: 39.99,
      category: "Accessories",
    },
    {
      id: 12,
      title: "Necklace",
      description: "Beautiful necklace with a pendant.",
      image: "https://example.com/images/necklace.jpg",
      price: 59.99,
      category: "Accessories",
    },
    {
      id: 13,
      title: "Bracelet",
      description: "Chic bracelet with an adjustable band.",
      image: "https://example.com/images/bracelet.jpg",
      price: 29.99,
      category: "Accessories",
    },
    {
      id: 14,
      title: "Keychain",
      description: "Stylish keychain with a leather strap.",
      image: "https://example.com/images/keychain.jpg",
      price: 12.99,
      category: "Accessories",
    },
    {
      id: 15,
      title: "Laptop Sleeve",
      description: "Protective laptop sleeve with a padded interior.",
      image: "https://example.com/images/laptop_sleeve.jpg",
      price: 39.99,
      category: "Accessories",
    },
  ],
  makeup: [
    {
      id: 1,
      title: "Lipstick",
      description: "Long-lasting matte lipstick available in various shades.",
      image: "https://example.com/images/lipstick.jpg",
      price: 15.99,
      category: "Girls Makeup",
    },
    {
      id: 2,
      title: "Foundation",
      description: "Full coverage liquid foundation for a flawless finish.",
      image: "https://example.com/images/foundation.jpg",
      price: 29.99,
      category: "Girls Makeup",
    },
    {
      id: 3,
      title: "Mascara",
      description: "Volumizing mascara for longer, thicker lashes.",
      image: "https://example.com/images/mascara.jpg",
      price: 12.99,
      category: "Girls Makeup",
    },
    {
      id: 4,
      title: "Eyeshadow Palette",
      description: "Eyeshadow palette with a range of vibrant colors.",
      image: "https://example.com/images/eyeshadow_palette.jpg",
      price: 19.99,
      category: "Girls Makeup",
    },
    {
      id: 5,
      title: "Blush",
      description: "Powder blush for a natural, rosy glow.",
      image: "https://example.com/images/blush.jpg",
      price: 9.99,
      category: "Girls Makeup",
    },
    {
      id: 6,
      title: "Highlighter",
      description: "Shimmering highlighter to accentuate your features.",
      image: "https://example.com/images/highlighter.jpg",
      price: 14.99,
      category: "Girls Makeup",
    },
    {
      id: 7,
      title: "Concealer",
      description: "Creamy concealer to cover blemishes and dark circles.",
      image: "https://example.com/images/concealer.jpg",
      price: 11.99,
      category: "Girls Makeup",
    },
    {
      id: 8,
      title: "Eyebrow Pencil",
      description: "Precision eyebrow pencil for defined brows.",
      image: "https://example.com/images/eyebrow_pencil.jpg",
      price: 8.99,
      category: "Girls Makeup",
    },
    {
      id: 9,
      title: "Lip Gloss",
      description: "Glossy lip gloss for a shiny, plump look.",
      image: "https://example.com/images/lip_gloss.jpg",
      price: 10.99,
      category: "Girls Makeup",
    },
    {
      id: 10,
      title: "Setting Spray",
      description: "Makeup setting spray for long-lasting wear.",
      image: "https://example.com/images/setting_spray.jpg",
      price: 13.99,
      category: "Girls Makeup",
    },
    {
      id: 11,
      title: "Primer",
      description: "Silicone-based primer for a smooth makeup base.",
      image: "https://example.com/images/primer.jpg",
      price: 18.99,
      category: "Girls Makeup",
    },
    {
      id: 12,
      title: "Contour Kit",
      description: "Contour kit with shades to sculpt and define.",
      image: "https://example.com/images/contour_kit.jpg",
      price: 24.99,
      category: "Girls Makeup",
    },
    {
      id: 13,
      title: "Eyeliner",
      description: "Waterproof eyeliner for a bold, precise look.",
      image: "https://example.com/images/eyeliner.jpg",
      price: 7.99,
      category: "Girls Makeup",
    },
    {
      id: 14,
      title: "Makeup Remover",
      description: "Gentle makeup remover for all skin types.",
      image: "https://example.com/images/makeup_remover.jpg",
      price: 9.99,
      category: "Girls Makeup",
    },
    {
      id: 15,
      title: "Bronzer",
      description: "Matte bronzer for a sun-kissed glow.",
      image: "https://example.com/images/bronzer.jpg",
      price: 16.99,
      category: "Girls Makeup",
    },
  ],
};
