import { IProductCollection } from "@/types";

export const productData: IProductCollection = {
  jackets: [
    {
      id: 1,
      title: "Classic Leather Jacket",
      description: "A timeless black leather jacket with a sleek design.",
      image: "https://example.com/images/leather_jacket.jpg",
      price: 120.99,
      category: "Jackets",
    },
    {
      id: 2,
      title: "Denim Jacket",
      description: "Stylish blue denim jacket perfect for casual wear.",
      image: "https://example.com/images/denim_jacket.jpg",
      price: 75.49,
      category: "Jackets",
    },
    {
      id: 3,
      title: "Bomber Jacket",
      description: "Trendy bomber jacket with a comfortable fit.",
      image: "https://example.com/images/bomber_jacket.jpg",
      price: 89.99,
      category: "Jackets",
    },
    {
      id: 4,
      title: "Parka Jacket",
      description: "Warm parka jacket with a fur-lined hood.",
      image: "https://example.com/images/parka_jacket.jpg",
      price: 149.99,
      category: "Jackets",
    },
    {
      id: 5,
      title: "Windbreaker Jacket",
      description: "Lightweight windbreaker jacket for outdoor activities.",
      image: "https://example.com/images/windbreaker_jacket.jpg",
      price: 59.99,
      category: "Jackets",
    },
    {
      id: 6,
      title: "Varsity Jacket",
      description: "Classic varsity jacket with a sporty look.",
      image: "https://example.com/images/varsity_jacket.jpg",
      price: 99.99,
      category: "Jackets",
    },
    {
      id: 7,
      title: "Peacoat Jacket",
      description: "Elegant peacoat jacket with a double-breasted design.",
      image: "https://example.com/images/peacoat_jacket.jpg",
      price: 129.99,
      category: "Jackets",
    },
    {
      id: 8,
      title: "Trench Coat",
      description: "Classic trench coat for a sophisticated look.",
      image: "https://example.com/images/trench_coat.jpg",
      price: 139.99,
      category: "Jackets",
    },
    {
      id: 9,
      title: "Quilted Jacket",
      description: "Comfortable quilted jacket with extra padding.",
      image: "https://example.com/images/quilted_jacket.jpg",
      price: 79.99,
      category: "Jackets",
    },
    {
      id: 10,
      title: "Hooded Jacket",
      description: "Casual hooded jacket perfect for everyday wear.",
      image: "https://example.com/images/hooded_jacket.jpg",
      price: 69.99,
      category: "Jackets",
    },
    {
      id: 11,
      title: "Field Jacket",
      description: "Durable field jacket with multiple pockets.",
      image: "https://example.com/images/field_jacket.jpg",
      price: 110.99,
      category: "Jackets",
    },
    {
      id: 12,
      title: "Fleece Jacket",
      description: "Warm fleece jacket for cold weather.",
      image: "https://example.com/images/fleece_jacket.jpg",
      price: 55.99,
      category: "Jackets",
    },
    {
      id: 13,
      title: "Suede Jacket",
      description: "Stylish suede jacket with a soft touch.",
      image: "https://example.com/images/suede_jacket.jpg",
      price: 115.99,
      category: "Jackets",
    },
    {
      id: 14,
      title: "Blazer Jacket",
      description: "Smart blazer jacket for formal occasions.",
      image: "https://example.com/images/blazer_jacket.jpg",
      price: 105.99,
      category: "Jackets",
    },
    {
      id: 15,
      title: "Down Jacket",
      description: "Insulated down jacket for extreme cold.",
      image: "https://example.com/images/down_jacket.jpg",
      price: 159.99,
      category: "Jackets",
    },
  ],
  sportswear: [
    {
      id: 1,
      title: "Running Shoes",
      description: "Lightweight running shoes designed for maximum comfort.",
      image: "https://example.com/images/running_shoes.jpg",
      price: 59.99,
      category: "Sportswear",
    },
    {
      id: 2,
      title: "Yoga Pants",
      description: "Flexible yoga pants perfect for any workout.",
      image: "https://example.com/images/yoga_pants.jpg",
      price: 39.99,
      category: "Sportswear",
    },
    {
      id: 3,
      title: "Fitness Tracker",
      description: "Wearable fitness tracker to monitor your activity.",
      image: "https://example.com/images/fitness_tracker.jpg",
      price: 129.99,
      category: "Sportswear",
    },
    {
      id: 4,
      title: "Sports Jacket",
      description: "Lightweight sports jacket for outdoor activities.",
      image: "https://example.com/images/sports_jacket.jpg",
      price: 49.99,
      category: "Sportswear",
    },
    {
      id: 5,
      title: "Basketball Shorts",
      description:
        "Comfortable basketball shorts with moisture-wicking fabric.",
      image: "https://example.com/images/basketball_shorts.jpg",
      price: 25.99,
      category: "Sportswear",
    },
    {
      id: 6,
      title: "Compression Shirt",
      description: "Tight-fitting compression shirt for enhanced performance.",
      image: "https://example.com/images/compression_shirt.jpg",
      price: 29.99,
      category: "Sportswear",
    },
    {
      id: 7,
      title: "Sports Bra",
      description: "Supportive sports bra for high-impact activities.",
      image: "https://example.com/images/sports_bra.jpg",
      price: 35.99,
      category: "Sportswear",
    },
    {
      id: 8,
      title: "Training Socks",
      description: "Comfortable and breathable training socks.",
      image: "https://example.com/images/training_socks.jpg",
      price: 12.99,
      category: "Sportswear",
    },
    {
      id: 9,
      title: "Track Pants",
      description: "Lightweight track pants for running and training.",
      image: "https://example.com/images/track_pants.jpg",
      price: 45.99,
      category: "Sportswear",
    },
    {
      id: 10,
      title: "Sports Cap",
      description: "Breathable sports cap to keep you cool.",
      image: "https://example.com/images/sports_cap.jpg",
      price: 19.99,
      category: "Sportswear",
    },
    {
      id: 11,
      title: "Sweatband",
      description: "Absorbent sweatband for intense workouts.",
      image: "https://example.com/images/sweatband.jpg",
      price: 9.99,
      category: "Sportswear",
    },
    {
      id: 12,
      title: "Running Tights",
      description: "Form-fitting running tights for optimal performance.",
      image: "https://example.com/images/running_tights.jpg",
      price: 39.99,
      category: "Sportswear",
    },
    {
      id: 13,
      title: "Training Gloves",
      description: "Protective training gloves for weightlifting.",
      image: "https://example.com/images/training_gloves.jpg",
      price: 24.99,
      category: "Sportswear",
    },
    {
      id: 14,
      title: "Hiking Boots",
      description: "Durable hiking boots for all terrains.",
      image: "https://example.com/images/hiking_boots.jpg",
      price: 89.99,
      category: "Sportswear",
    },
    {
      id: 15,
      title: "Cycling Jersey",
      description: "Breathable cycling jersey with a comfortable fit.",
      image: "https://example.com/images/cycling_jersey.jpg",
      price: 59.99,
      category: "Sportswear",
    },
  ],
  shoes: [
    {
      id: 1,
      title: "Running Shoes",
      description: "Lightweight running shoes designed for maximum comfort.",
      image: "https://example.com/images/running_shoes.jpg",
      price: 59.99,
      category: "Shoes",
    },
    {
      id: 2,
      title: "Basketball Shoes",
      description: "High-top basketball shoes with excellent ankle support.",
      image: "https://example.com/images/basketball_shoes.jpg",
      price: 89.99,
      category: "Shoes",
    },
    {
      id: 3,
      title: "Soccer Cleats",
      description: "Durable soccer cleats for firm ground surfaces.",
      image: "https://example.com/images/soccer_cleats.jpg",
      price: 79.99,
      category: "Shoes",
    },
    {
      id: 4,
      title: "Tennis Shoes",
      description: "Comfortable tennis shoes with a non-marking sole.",
      image: "https://example.com/images/tennis_shoes.jpg",
      price: 69.99,
      category: "Shoes",
    },
    {
      id: 5,
      title: "Hiking Boots",
      description: "Rugged hiking boots for all terrains.",
      image: "https://example.com/images/hiking_boots.jpg",
      price: 99.99,
      category: "Shoes",
    },
    {
      id: 6,
      title: "Casual Sneakers",
      description: "Stylish casual sneakers for everyday wear.",
      image: "https://example.com/images/casual_sneakers.jpg",
      price: 49.99,
      category: "Shoes",
    },
    {
      id: 7,
      title: "Dress Shoes",
      description: "Elegant dress shoes for formal occasions.",
      image: "https://example.com/images/dress_shoes.jpg",
      price: 109.99,
      category: "Shoes",
    },
    {
      id: 8,
      title: "Slip-On Shoes",
      description: "Convenient slip-on shoes with a comfortable fit.",
      image: "https://example.com/images/slip_on_shoes.jpg",
      price: 39.99,
      category: "Shoes",
    },
    {
      id: 9,
      title: "Loafers",
      description: "Classic loafers for a casual yet polished look.",
      image: "https://example.com/images/loafers.jpg",
      price: 69.99,
      category: "Shoes",
    },
    {
      id: 10,
      title: "Sandals",
      description: "Comfortable sandals for warm weather.",
      image: "https://example.com/images/sandals.jpg",
      price: 29.99,
      category: "Shoes",
    },
    {
      id: 11,
      title: "Running Shoes",
      description: "High-performance running shoes for athletes.",
      image: "https://example.com/images/high_performance_running_shoes.jpg",
      price: 99.99,
      category: "Shoes",
    },
    {
      id: 12,
      title: "Golf Shoes",
      description: "Water-resistant golf shoes with excellent grip.",
      image: "https://example.com/images/golf_shoes.jpg",
      price: 79.99,
      category: "Shoes",
    },
    {
      id: 13,
      title: "Skate Shoes",
      description: "Durable skate shoes with a grippy sole.",
      image: "https://example.com/images/skate_shoes.jpg",
      price: 59.99,
      category: "Shoes",
    },
    {
      id: 14,
      title: "Climbing Shoes",
      description: "Specialized climbing shoes with a snug fit.",
      image: "https://example.com/images/climbing_shoes.jpg",
      price: 89.99,
      category: "Shoes",
    },
    {
      id: 15,
      title: "Water Shoes",
      description: "Quick-drying water shoes for aquatic activities.",
      image: "https://example.com/images/water_shoes.jpg",
      price: 39.99,
      category: "Shoes",
    },
  ],
  accessories: [
    {
      id: 1,
      title: "Sunglasses",
      description: "Stylish sunglasses with UV protection.",
      image: "https://example.com/images/sunglasses.jpg",
      price: 25.99,
      category: "Accessories",
    },
    {
      id: 2,
      title: "Leather Wallet",
      description: "Durable leather wallet with multiple compartments.",
      image: "https://example.com/images/leather_wallet.jpg",
      price: 49.99,
      category: "Accessories",
    },
    {
      id: 3,
      title: "Wristwatch",
      description: "Elegant wristwatch with a stainless steel band.",
      image: "https://example.com/images/wristwatch.jpg",
      price: 129.99,
      category: "Accessories",
    },
    {
      id: 4,
      title: "Baseball Cap",
      description: "Casual baseball cap with adjustable strap.",
      image: "https://example.com/images/baseball_cap.jpg",
      price: 19.99,
      category: "Accessories",
    },
    {
      id: 5,
      title: "Scarf",
      description: "Warm and stylish scarf for cold weather.",
      image: "https://example.com/images/scarf.jpg",
      price: 29.99,
      category: "Accessories",
    },
    {
      id: 6,
      title: "Backpack",
      description: "Spacious backpack with multiple pockets.",
      image: "https://example.com/images/backpack.jpg",
      price: 69.99,
      category: "Accessories",
    },
    {
      id: 7,
      title: "Belt",
      description: "Leather belt with a classic buckle.",
      image: "https://example.com/images/belt.jpg",
      price: 34.99,
      category: "Accessories",
    },
    {
      id: 8,
      title: "Beanie",
      description: "Comfortable beanie for chilly days.",
      image: "https://example.com/images/beanie.jpg",
      price: 15.99,
      category: "Accessories",
    },
    {
      id: 9,
      title: "Tie",
      description: "Silk tie for formal occasions.",
      image: "https://example.com/images/tie.jpg",
      price: 24.99,
      category: "Accessories",
    },
    {
      id: 10,
      title: "Gloves",
      description: "Warm gloves with a touchscreen-compatible design.",
      image: "https://example.com/images/gloves.jpg",
      price: 19.99,
      category: "Accessories",
    },
    {
      id: 11,
      title: "Earrings",
      description: "Elegant earrings with a minimalist design.",
      image: "https://example.com/images/earrings.jpg",
      price: 39.99,
      category: "Accessories",
    },
    {
      id: 12,
      title: "Necklace",
      description: "Beautiful necklace with a pendant.",
      image: "https://example.com/images/necklace.jpg",
      price: 59.99,
      category: "Accessories",
    },
    {
      id: 13,
      title: "Bracelet",
      description: "Chic bracelet with an adjustable band.",
      image: "https://example.com/images/bracelet.jpg",
      price: 29.99,
      category: "Accessories",
    },
    {
      id: 14,
      title: "Keychain",
      description: "Stylish keychain with a leather strap.",
      image: "https://example.com/images/keychain.jpg",
      price: 12.99,
      category: "Accessories",
    },
    {
      id: 15,
      title: "Laptop Sleeve",
      description: "Protective laptop sleeve with a padded interior.",
      image: "https://example.com/images/laptop_sleeve.jpg",
      price: 39.99,
      category: "Accessories",
    },
  ],
  makeup: [
    {
      id: 1,
      title: "Lipstick",
      description: "Long-lasting matte lipstick available in various shades.",
      image: "https://example.com/images/lipstick.jpg",
      price: 15.99,
      category: "Girls Makeup",
    },
    {
      id: 2,
      title: "Foundation",
      description: "Full coverage liquid foundation for a flawless finish.",
      image: "https://example.com/images/foundation.jpg",
      price: 29.99,
      category: "Girls Makeup",
    },
    {
      id: 3,
      title: "Mascara",
      description: "Volumizing mascara for longer, thicker lashes.",
      image: "https://example.com/images/mascara.jpg",
      price: 12.99,
      category: "Girls Makeup",
    },
    {
      id: 4,
      title: "Eyeshadow Palette",
      description: "Eyeshadow palette with a range of vibrant colors.",
      image: "https://example.com/images/eyeshadow_palette.jpg",
      price: 19.99,
      category: "Girls Makeup",
    },
    {
      id: 5,
      title: "Blush",
      description: "Powder blush for a natural, rosy glow.",
      image: "https://example.com/images/blush.jpg",
      price: 9.99,
      category: "Girls Makeup",
    },
    {
      id: 6,
      title: "Highlighter",
      description: "Shimmering highlighter to accentuate your features.",
      image: "https://example.com/images/highlighter.jpg",
      price: 14.99,
      category: "Girls Makeup",
    },
    {
      id: 7,
      title: "Concealer",
      description: "Creamy concealer to cover blemishes and dark circles.",
      image: "https://example.com/images/concealer.jpg",
      price: 11.99,
      category: "Girls Makeup",
    },
    {
      id: 8,
      title: "Eyebrow Pencil",
      description: "Precision eyebrow pencil for defined brows.",
      image: "https://example.com/images/eyebrow_pencil.jpg",
      price: 8.99,
      category: "Girls Makeup",
    },
    {
      id: 9,
      title: "Lip Gloss",
      description: "Glossy lip gloss for a shiny, plump look.",
      image: "https://example.com/images/lip_gloss.jpg",
      price: 10.99,
      category: "Girls Makeup",
    },
    {
      id: 10,
      title: "Setting Spray",
      description: "Makeup setting spray for long-lasting wear.",
      image: "https://example.com/images/setting_spray.jpg",
      price: 13.99,
      category: "Girls Makeup",
    },
    {
      id: 11,
      title: "Primer",
      description: "Silicone-based primer for a smooth makeup base.",
      image: "https://example.com/images/primer.jpg",
      price: 18.99,
      category: "Girls Makeup",
    },
    {
      id: 12,
      title: "Contour Kit",
      description: "Contour kit with shades to sculpt and define.",
      image: "https://example.com/images/contour_kit.jpg",
      price: 24.99,
      category: "Girls ",
    },
    {
      id: 13,
      title: "Eyeliner",
      description: "Waterproof eyeliner for a bold, precise look.",
      image: "https://example.com/images/eyeliner.jpg",
      price: 7.99,
      category: "Girls Makeup",
    },
    {
      id: 14,
      title: "Makeup Remover",
      description: "Gentle makeup remover for all skin types.",
      image: "https://example.com/images/makeup_remover.jpg",
      price: 9.99,
      category: "Girls Makeup",
    },
    {
      id: 15,
      title: "Bronzer",
      description: "Matte bronzer for a sun-kissed glow.",
      image: "https://example.com/images/bronzer.jpg",
      price: 16.99,
      category: "Girls Makeup",
    },
  ],

  dresses: [
    {
      id: 1,
      title: "Evening Gown",
      description: "Elegant evening gown suitable for formal events.",
      image: "https://example.com/images/evening_gown.jpg",
      price: 129.99,
      category: "Dresses",
    },
    {
      id: 2,
      title: "Maxi Dress",
      description: "Flowy maxi dress with a bohemian vibe.",
      image: "https://example.com/images/maxi_dress.jpg",
      price: 69.99,
      category: "Dresses",
    },
    {
      id: 3,
      title: "Shift Dress",
      description: "Comfortable shift dress for everyday wear.",
      image: "https://example.com/images/shift_dress.jpg",
      price: 44.99,
      category: "Dresses",
    },
    {
      id: 4,
      title: "T-shirt Dress",
      description: "Casual t-shirt dress for a relaxed look.",
      image: "https://example.com/images/t_shirt_dress.jpg",
      price: 34.99,
      category: "Dresses",
    },
    {
      id: 5,
      title: "Denim Dress",
      description: "Trendy denim dress for a casual outfit.",
      image: "https://example.com/images/denim_dress.jpg",
      price: 59.99,
      category: "Dresses",
    },
    {
      id: 6,
      title: "Floral Summer Dress",
      description: "Lightweight floral summer dress perfect for warm weather.",
      image: "https://example.com/images/floral_summer_dress.jpg",
      price: 49.99,
      category: "Dresses",
    },
    {
      id: 7,
      title: "Bodycon Dress",
      description: "Stylish bodycon dress for a sleek silhouette.",
      image: "https://example.com/images/bodycon_dress.jpg",
      price: 59.99,
      category: "Dresses",
    },
    {
      id: 8,
      title: "Casual Midi Dress",
      description: "Comfortable midi dress for casual outings.",
      image: "https://example.com/images/casual_midi_dress.jpg",
      price: 39.99,
      category: "Dresses",
    },
    {
      id: 9,
      title: "Wrap Dress",
      description: "Versatile wrap dress that flatters all body types.",
      image: "https://example.com/images/wrap_dress.jpg",
      price: 54.99,
      category: "Dresses",
    },
    {
      id: 10,
      title: "Sheath Dress",
      description: "Sophisticated sheath dress for a polished look.",
      image: "https://example.com/images/sheath_dress.jpg",
      price: 79.99,
      category: "Dresses",
    },
    {
      id: 11,
      title: "Shift Dress",
      description: "Comfortable shift dress for everyday wear.",
      image: "https://example.com/images/shift_dress.jpg",
      price: 44.99,
      category: "Dresses",
    },
    {
      id: 12,
      title: "Peplum Dress",
      description: "Flirty peplum dress with a feminine touch.",
      image: "https://example.com/images/peplum_dress.jpg",
      price: 74.99,
      category: "Dresses",
    },
    {
      id: 13,
      title: "Slip Dress",
      description: "Minimalist slip dress with a sleek design.",
      image: "https://example.com/images/slip_dress.jpg",
      price: 49.99,
      category: "Dresses",
    },
    {
      id: 14,
      title: "Lace Dress",
      description: "Romantic lace dress for special occasions.",
      image: "https://example.com/images/lace_dress.jpg",
      price: 99.99,
      category: "Dresses",
    },
    {
      id: 15,
      title: "A-line Dress",
      description: "Classic A-line dress with a modern twist.",
      image: "https://example.com/images/a_line_dress.jpg",
      price: 64.99,
      category: "Dresses",
    },
  ],
  shirts: [
    {
      id: 1,
      title: "Striped Button-Up",
      description: "Chic striped button-up shirt for a polished appearance.",
      image: "https://example.com/images/striped_button_up.jpg",
      price: 34.99,
      category: "Shirts",
    },
    {
      id: 2,
      title: "Peasant Top",
      description: "Bohemian peasant top with intricate embroidery.",
      image: "https://example.com/images/peasant_top.jpg",
      price: 37.99,
      category: "Shirts",
    },
    {
      id: 3,
      title: "Silk Blouse",
      description: "Elegant silk blouse perfect for formal occasions.",
      image: "https://example.com/images/silk_blouse.jpg",
      price: 49.99,
      category: "Shirts",
    },
    {
      id: 4,
      title: "Striped Button-Up",
      description: "Chic striped button-up shirt for a polished appearance.",
      image: "https://example.com/images/striped_button_up.jpg",
      price: 34.99,
      category: "Shirts",
    },
    {
      id: 5,
      title: "Plaid Flannel Shirt",
      description: "Cozy plaid flannel shirt for cooler weather.",
      image: "https://example.com/images/plaid_flannel_shirt.jpg",
      price: 27.99,
      category: "Shirts",
    },
    {
      id: 6,
      title: "Chambray Shirt",
      description: "Lightweight chambray shirt for a casual look.",
      image: "https://example.com/images/chambray_shirt.jpg",
      price: 29.99,
      category: "Shirts",
    },
    {
      id: 7,
      title: "Off-Shoulder Blouse",
      description: "Stylish off-shoulder blouse for a trendy look.",
      image: "https://example.com/images/off_shoulder_blouse.jpg",
      price: 34.99,
      category: "Shirts",
    },
    {
      id: 8,
      title: "Mock Neck Top",
      description: "Sophisticated mock neck top for a chic look.",
      image: "https://example.com/images/mock_neck_top.jpg",
      price: 35.99,
      category: "Shirts",
    },
    {
      id: 9,
      title: "Tie-Front Shirt",
      description: "Casual tie-front shirt for a laid-back style.",
      image: "https://example.com/images/tie_front_shirt.jpg",
      price: 32.99,
      category: "Shirts",
    },
    {
      id: 10,
      title: "Printed Blouse",
      description: "Colorful printed blouse to brighten your wardrobe.",
      image: "https://example.com/images/printed_blouse.jpg",
      price: 38.99,
      category: "Shirts",
    },
    {
      id: 11,
      title: "Bell Sleeve Shirt",
      description: "Elegant bell sleeve shirt with a modern design.",
      image: "https://example.com/images/bell_sleeve_shirt.jpg",
      price: 42.99,
      category: "Shirts",
    },
    {
      id: 12,
      title: "Ruffle Sleeve Top",
      description: "Playful ruffle sleeve top for a fun outfit.",
      image: "https://example.com/images/ruffle_sleeve_top.jpg",
      price: 28.99,
      category: "Shirts",
    },
    {
      id: 13,
      title: "Lace Top",
      description: "Feminine lace top with delicate detailing.",
      image: "https://example.com/images/lace_top.jpg",
      price: 44.99,
      category: "Shirts",
    },
    {
      id: 14,
      title: "Classic White Shirt",
      description: "Timeless white shirt that pairs well with any outfit.",
      image: "https://example.com/images/classic_white_shirt.jpg",
      price: 29.99,
      category: "Shirts",
    },
    {
      id: 15,
      title: "Graphic Tee",
      description: "Trendy graphic tee with a bold print.",
      image: "https://example.com/images/graphic_tee.jpg",
      price: 19.99,
      category: "Shirts",
    },
  ],

  tshirts: [
    {
      id: 1,
      title: "Graphic T-Shirt",
      description: "Trendy graphic t-shirt with a bold print.",
      image: "https://example.com/images/graphic_tshirt.jpg",
      price: 19.99,
      category: "T-Shirts",
    },
    {
      id: 2,
      title: "Muscle Tee",
      description: "Sleeveless muscle tee for a sporty look.",
      image: "https://example.com/images/muscle_tee.jpg",
      price: 13.99,
      category: "T-Shirts",
    },
    {
      id: 3,
      title: "Pocket T-Shirt",
      description: "Basic t-shirt with a front pocket detail.",
      image: "https://example.com/images/pocket_tshirt.jpg",
      price: 14.99,
      category: "T-Shirts",
    },
    {
      id: 4,
      title: "Ringer T-Shirt",
      description: "Retro ringer t-shirt with contrast trim.",
      image: "https://example.com/images/ringer_tshirt.jpg",
      price: 16.99,
      category: "T-Shirts",
    },
    {
      id: 5,
      title: "Oversized T-Shirt",
      description: "Comfortable oversized t-shirt for a relaxed fit.",
      image: "https://example.com/images/oversized_tshirt.jpg",
      price: 18.99,
      category: "T-Shirts",
    },
    {
      id: 6,
      title: "Embroidered T-Shirt",
      description: "Delicate embroidered t-shirt for a feminine touch.",
      image: "https://example.com/images/embroidered_tshirt.jpg",
      price: 22.99,
      category: "T-Shirts",
    },
    {
      id: 7,
      title: "Crop Top T-Shirt",
      description: "Stylish crop top t-shirt for a trendy outfit.",
      image: "https://example.com/images/crop_top_tshirt.jpg",
      price: 15.99,
      category: "T-Shirts",
    },
    {
      id: 8,
      title: "Slub T-Shirt",
      description: "Textured slub t-shirt for a casual look.",
      image: "https://example.com/images/slub_tshirt.jpg",
      price: 15.99,
      category: "T-Shirts",
    },
    {
      id: 9,
      title: "Tie-Dye T-Shirt",
      description: "Fun tie-dye t-shirt for a vibrant look.",
      image: "https://example.com/images/tie_dye_tshirt.jpg",
      price: 21.99,
      category: "T-Shirts",
    },
    {
      id: 10,
      title: "Basic White T-Shirt",
      description: "Classic white t-shirt that goes with everything.",
      image: "https://example.com/images/basic_white_tshirt.jpg",
      price: 14.99,
      category: "T-Shirts",
    },
    {
      id: 11,
      title: "Henley T-Shirt",
      description: "Casual henley t-shirt with a button placket.",
      image: "https://example.com/images/henley_tshirt.jpg",
      price: 18.99,
      category: "T-Shirts",
    },
    {
      id: 12,
      title: "Raglan T-Shirt",
      description: "Classic raglan t-shirt with contrasting sleeves.",
      image: "https://example.com/images/raglan_tshirt.jpg",
      price: 17.99,
      category: "T-Shirts",
    },
    {
      id: 13,
      title: "Striped T-Shirt",
      description: "Casual striped t-shirt for a laid-back look.",
      image: "https://example.com/images/striped_tshirt.jpg",
      price: 17.99,
      category: "T-Shirts",
    },
    {
      id: 14,
      title: "Long Sleeve T-Shirt",
      description: "Comfortable long sleeve t-shirt for cooler days.",
      image: "https://example.com/images/long_sleeve_tshirt.jpg",
      price: 20.99,
      category: "T-Shirts",
    },
    {
      id: 15,
      title: "Pocket T-Shirt",
      description: "Basic t-shirt with a front pocket detail.",
      image: "https://example.com/images/pocket_tshirt.jpg",
      price: 14.99,
      category: "T-Shirts",
    },
  ],

  jeans: [
    {
      id: 1,
      title: "Flared Jeans",
      description: "Trendy flared jeans for a retro style.",
      image: "https://example.com/images/flared_jeans.jpg",
      price: 59.99,
      category: "Jeans",
    },
    {
      id: 2,
      title: "Cropped Jeans",
      description: "Cropped jeans for a chic, modern look.",
      image: "https://example.com/images/cropped_jeans.jpg",
      price: 45.99,
      category: "Jeans",
    },
    {
      id: 3,
      title: "Patchwork Jeans",
      description: "Unique patchwork jeans with a creative design.",
      image: "https://example.com/images/patchwork_jeans.jpg",
      price: 64.99,
      category: "Jeans",
    },
    {
      id: 4,
      title: "Skinny Jeans",
      description: "Classic skinny jeans with a snug fit.",
      image: "https://example.com/images/skinny_jeans.jpg",
      price: 49.99,
      category: "Jeans",
    },
    {
      id: 5,
      title: "Boyfriend Jeans",
      description: "Relaxed fit boyfriend jeans for a casual look.",
      image: "https://example.com/images/boyfriend_jeans.jpg",
      price: 44.99,
      category: "Jeans",
    },
    {
      id: 6,
      title: "Straight Leg Jeans",
      description: "Timeless straight leg jeans for a versatile look.",
      image: "https://example.com/images/straight_leg_jeans.jpg",
      price: 49.99,
      category: "Jeans",
    },
    {
      id: 7,
      title: "Distressed Jeans",
      description: "Stylish distressed jeans with a worn-in look.",
      image: "https://example.com/images/distressed_jeans.jpg",
      price: 54.99,
      category: "Jeans",
    },
    {
      id: 8,
      title: "High-Waisted Jeans",
      description: "High-waisted jeans for a flattering silhouette.",
      image: "https://example.com/images/high_waisted_jeans.jpg",
      price: 54.99,
      category: "Jeans",
    },
    {
      id: 9,
      title: "Bootcut Jeans",
      description: "Bootcut jeans with a slight flare at the bottom.",
      image: "https://example.com/images/bootcut_jeans.jpg",
      price: 59.99,
      category: "Jeans",
    },
    {
      id: 10,
      title: "Low-Rise Jeans",
      description: "Trendy low-rise jeans for a casual look.",
      image: "https://example.com/images/low_rise_jeans.jpg",
      price: 49.99,
      category: "Jeans",
    },
    {
      id: 11,
      title: "Wide Leg Jeans",
      description: "Comfortable wide leg jeans for a relaxed fit.",
      image: "https://example.com/images/wide_leg_jeans.jpg",
      price: 49.99,
      category: "Jeans",
    },
    {
      id: 12,
      title: "Jeggings",
      description: "Stretchy jeggings that combine style and comfort.",
      image: "https://example.com/images/jeggings.jpg",
      price: 39.99,
      category: "Jeans",
    },
    {
      id: 13,
      title: "Mom Jeans",
      description: "Comfortable mom jeans with a relaxed fit.",
      image: "https://example.com/images/mom_jeans.jpg",
      price: 49.99,
      category: "Jeans",
    },
    {
      id: 14,
      title: "Embroidered Jeans",
      description: "Stylish embroidered jeans with intricate details.",
      image: "https://example.com/images/embroidered_jeans.jpg",
      price: 59.99,
      category: "Jeans",
    },
    {
      id: 15,
      title: "Ripped Jeans",
      description: "Fashion-forward ripped jeans with edgy details.",
      image: "https://example.com/images/ripped_jeans.jpg",
      price: 54.99,
      category: "Jeans",
    },
  ],

  swimwear: [
    {
      id: 1,
      title: "One-Piece Swimsuit",
      description: "Elegant one-piece swimsuit with a flattering fit.",
      image: "https://example.com/images/one_piece_swimsuit.jpg",
      price: 39.99,
      category: "Swimwear",
    },
    {
      id: 2,
      title: "Swim Dress",
      description: "Stylish swim dress with a flowy skirt.",
      image: "https://example.com/images/swim_dress.jpg",
      price: 44.99,
      category: "Swimwear",
    },
    {
      id: 3,
      title: "Monokini",
      description: "Trendy monokini with cut-out details.",
      image: "https://example.com/images/monokini.jpg",
      price: 42.99,
      category: "Swimwear",
    },
    {
      id: 4,
      title: "Tankini Set",
      description: "Comfortable tankini set for extra coverage.",
      image: "https://example.com/images/tankini_set.jpg",
      price: 34.99,
      category: "Swimwear",
    },
    {
      id: 5,
      title: "Swim Shorts",
      description: "Comfortable swim shorts for active beach days.",
      image: "https://example.com/images/swim_shorts.jpg",
      price: 24.99,
      category: "Swimwear",
    },
    {
      id: 6,
      title: "Fringe Swimsuit",
      description: "Fun fringe swimsuit with playful tassels.",
      image: "https://example.com/images/fringe_swimsuit.jpg",
      price: 43.99,
      category: "Swimwear",
    },
    {
      id: 7,
      title: "High-Waisted Bikini",
      description: "Vintage-inspired high-waisted bikini set.",
      image: "https://example.com/images/high_waisted_bikini.jpg",
      price: 37.99,
      category: "Swimwear",
    },
    {
      id: 8,
      title: "Plunge Swimsuit",
      description: "Bold plunge swimsuit with deep V-neckline.",
      image: "https://example.com/images/plunge_swimsuit.jpg",
      price: 41.99,
      category: "Swimwear",
    },
    {
      id: 9,
      title: "Swim Skirt",
      description: "Flattering swim skirt with attached briefs.",
      image: "https://example.com/images/swim_skirt.jpg",
      price: 34.99,
      category: "Swimwear",
    },
    {
      id: 10,
      title: "Bikini Set",
      description: "Classic bikini set with adjustable straps.",
      image: "https://example.com/images/bikini_set.jpg",
      price: 29.99,
      category: "Swimwear",
    },
    {
      id: 11,
      title: "Rash Guard",
      description: "Protective rash guard for sun and surf.",
      image: "https://example.com/images/rash_guard.jpg",
      price: 29.99,
      category: "Swimwear",
    },
    {
      id: 12,
      title: "Sporty Bikini",
      description: "Athletic bikini set for active swimmers.",
      image: "https://example.com/images/sporty_bikini.jpg",
      price: 36.99,
      category: "Swimwear",
    },
    {
      id: 13,
      title: "Wrap Bikini",
      description: "Stylish wrap bikini set with tie details.",
      image: "https://example.com/images/wrap_bikini.jpg",
      price: 38.99,
      category: "Swimwear",
    },
    {
      id: 14,
      title: "Underwire Swimsuit",
      description: "Supportive underwire swimsuit for added lift.",
      image: "https://example.com/images/underwire_swimsuit.jpg",
      price: 39.99,
      category: "Swimwear",
    },
    {
      id: 15,
      title: "Bandeau Bikini",
      description: "Chic bandeau bikini set with a strapless design.",
      image: "https://example.com/images/bandeau_bikini.jpg",
      price: 32.99,
      category: "Swimwear",
    },
  ],
};
